region              = "us-east-1"
profile             = "personal"
group               = "huge-8"
application         = "site"
env                 = "nonprod"
color               = "blue"
created_by          = "richard.bielski"
comment             = "infrastructure for big-8 site"